-- Databricks notebook source
-- MAGIC %md-sandbox
-- MAGIC
-- MAGIC # AI / BI On Databricks: Genie
-- MAGIC
-- MAGIC <img style="float: right; margin-top: 10px" width="700px" src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/retail/lakehouse-churn/lakehouse-retail-churn-ai-bi.png?raw=true" />
-- MAGIC
-- MAGIC
-- MAGIC Once your data ready, you can share it with your business users leveraging Databricks AI/BI Genie. 
-- MAGIC
-- MAGIC The data used to answer questions can be coming from your Dashboard dataset, or from any Unity Catalog table.
-- MAGIC
-- MAGIC Get started now! <a href="/data-rooms">Create a Genie room</a>, share it with your business user and ask any question!
-- MAGIC
-- MAGIC Under the hood, the Data Intelligence Platform anaylize and understands your data, making it possible to translate your own business language to SQL query and Visualizations!
-- MAGIC
-- MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/retail/lakehouse-churn/lakehouse-retail-c360-dashboard-genie.png?raw=true" style="float: left" width="400px">
-- MAGIC
-- MAGIC <!-- Collect usage data (view). Remove it to disable collection or disable tracker during installation. View README for more details.  -->
-- MAGIC <img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=lakehouse&notebook=03.2-AI-BI-Genie&demo_name=lakehouse-retail-c360&event=VIEW">

-- COMMAND ----------

-- MAGIC %md
-- MAGIC
-- MAGIC # Taking our analysis one step further: Predicting Churn
-- MAGIC
-- MAGIC Being able to run analysis on our past data already gives us a lot of insight. We can better understand which customers are churning evaluate the churn impact.
-- MAGIC
-- MAGIC However, knowing that we have churn isn't enough. We now need to take it to the next level and build a predictive model to determine our customers at risk of churn to be able to increase our revenue.
-- MAGIC
-- MAGIC Let's see how this can be done with [Databricks Machine Learning notebook]($../04-Data-Science-ML/04.1-automl-churn-prediction) | go [Go back to the introduction]($../00-churn-introduction-lakehouse)
