# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# DBTITLE 1,Explore Input data from CDC
display(spark.read.json("/Volumes/main__build/dbdemos_sdp_cdc/raw_data/customers"))
