# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

catalog = "main__build"
schema = dbName = db = "dbdemos_fsi_smart_claims"
volume_name = "volume_claims"

# COMMAND ----------

#Explore raw claims data

sdf = spark.read.format("json").load(f"/Volumes/{catalog}/{db}/{volume_name}/Claims")
display(sdf)

# COMMAND ----------

#Explore raw policy data
sdf = spark.read.format("csv").option("header", True).load(f"/Volumes/{catalog}/{db}/{volume_name}/Policies")
display(sdf)

# COMMAND ----------

#Explore raw telematics data

sdf = spark.read.format("parquet").load(f"/Volumes/{catalog}/{db}/{volume_name}/Telematics")
display(sdf)
