-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_zone/encounters", format => "parquet" )

-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_zone/patients", format => "parquet");

-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_zone/conditions", format => "parquet");


-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_zone/medications", format => "parquet");


-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_zone/immunizations", format => "parquet");


-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_vocab/CONCEPT", format => "parquet");


-- COMMAND ----------

SELECT * FROM read_files("/Volumes/main__build/lakehouse_hls_readmission/synthea/landing_vocab/CONCEPT_RELATIONSHIP", format => "parquet");
