-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

-- MAGIC %python
-- MAGIC catalog = "main__build"
-- MAGIC schema = dbName = db = "dbdemos_fsi_fraud_detection"
-- MAGIC volume_name = "fraud_raw_data"

-- COMMAND ----------

-- DBTITLE 1,Explore raw transaction data (JSON)
-- MAGIC %python
-- MAGIC sdf = spark.read.json(f"/Volumes/{catalog}/{db}/{volume_name}/transactions")
-- MAGIC display(sdf)

-- COMMAND ----------

-- DBTITLE 1,Explore raw customer data (CSV)
-- MAGIC %python
-- MAGIC sdf = spark.read.format("csv").option("header", True).option("multiLine", True).load(f"/Volumes/{catalog}/{db}/{volume_name}/customers")
-- MAGIC display(sdf)

-- COMMAND ----------

-- DBTITLE 1,Explore country reference data (CSV)
-- MAGIC %python
-- MAGIC sdf = spark.read.format("csv").option("header", True).load(f"/Volumes/{catalog}/{db}/{volume_name}/country_code")
-- MAGIC display(sdf)

-- COMMAND ----------

-- DBTITLE 1,Explore fraud reports (CSV)
-- MAGIC %python
-- MAGIC sdf = spark.read.format("csv").option("header", True).load(f"/Volumes/{catalog}/{db}/{volume_name}/fraud_report")
-- MAGIC display(sdf)
