# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

#Explore raw user data

sdf = spark.read.format("json").load("/Volumes/main__build/dbdemos_retail_c360/c360/users")
display(sdf)

# COMMAND ----------

#Explore raw order data
sdf = spark.read.format("json").load("/Volumes/main__build/dbdemos_retail_c360/c360/orders")
display(sdf)

# COMMAND ----------

#Explore raw event data

sdf = spark.read.format("csv").option("header", True).load("/Volumes/main__build/dbdemos_retail_c360/c360/events")
display(sdf)
