-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

--Explore raw historical turbine status data

SELECT * FROM json.`/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/historical_turbine_status`

-- COMMAND ----------

--Explore raw sensor data
SELECT * FROM parquet.`/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/incoming_data`

-- COMMAND ----------

--Explore raw turbine data

SELECT * FROM json.`/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/turbine`

