# Databricks notebook source
# MAGIC %md
# MAGIC # Let's improve and release a new model version in our repo using XGBoost
# MAGIC
# MAGIC As a Data Scientist, we realized that we could better detect fraud with XGboost if we add more custom logic to deal with imbalanced class.
# MAGIC
# MAGIC ## Dealing with Imbalanced class
# MAGIC
# MAGIC Let's improve the generated notebook to better handle our imbalanced fraud dataset with 2 basic steps:
# MAGIC
# MAGIC * Add more weight to the classes relatively to their frequence (this will penalize more the model if it doesn't classify the fraud properly)
# MAGIC * Switch the model to XGBoost
# MAGIC
# MAGIC *Note: Again, the goal of this notebook isn't to show a state of the art Fraud detection Model & imbalanced class. For more details on how to achieve that, please reach your Databricks Account team.*
# MAGIC
# MAGIC ## Bootstraping our custom model using the last AutoML run
# MAGIC
# MAGIC To speedup things, we'll re-use our last AutoML run containing all best practices and use it to switch to XGBoost + change our class weights.
# MAGIC
# MAGIC <!-- Collect usage data (view). Remove it to disable collection. View README for more details.  -->
# MAGIC <img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=lakehouse&notebook=04.4-Upgrade-to-imbalance-and-xgboost-model-fraud&demo_name=lakehouse-fsi-fraud-detection&event=VIEW">

# COMMAND ----------

# MAGIC %pip install databricks-sdk mlflow==3.14.0 databricks-feature-engineering scikit-learn xgboost
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %run ../_resources/00-setup $reset_all_data=false

# COMMAND ----------

# MAGIC %md
# MAGIC ## Bootstrapping our XGBoost upgrade with Databricks Genie Code
# MAGIC We ask Genie Code to upgrade our model to XGBoost and handle the class imbalance. Below is the
# MAGIC self-contained training code it generated: a scikit-learn pipeline with an XGBoost classifier,
# MAGIC balanced sample weights, fully tracked in MLflow with dataset lineage.

# COMMAND ----------

# DBTITLE 1,XGBoost + class weights, generated by Databricks Genie Code
import mlflow
from mlflow.models.signature import infer_signature
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.utils import class_weight
from sklearn.metrics import f1_score
from xgboost import XGBClassifier
from databricks.feature_engineering import FeatureEngineeringClient

model_name = "dbdemos_fsi_fraud"
target_col = "is_fraud"
xp_path = "/Shared/dbdemos/experiments/lakehouse-fsi-fraud-detection"
mlflow.set_experiment(xp_path)
DBDemos.set_experiment_permission(xp_path)

fe = FeatureEngineeringClient()
pdf = fe.read_table(name=f"{catalog}.{db}.transactions_features").sample(0.02).toPandas().drop(columns=["id"], errors="ignore")
# XGBoost needs an integer target
pdf[target_col] = pdf[target_col].astype(int)
X = pdf.drop(columns=[target_col])
y = pdf[target_col]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

num_cols = X.select_dtypes(include="number").columns.tolist()
cat_cols = [c for c in X.columns if c not in num_cols]
preprocessor = ColumnTransformer([
    ("num", SimpleImputer(strategy="median"), num_cols),
    ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")),
                      ("enc", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1))]), cat_cols),
])
pipeline = Pipeline([("preprocessor", preprocessor),
                     ("classifier", XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.1,
                                                  eval_metric="logloss", random_state=42))])

# Handle the imbalanced fraud classes by weighting samples inversely to class frequency.
sample_weights = class_weight.compute_sample_weight(class_weight="balanced", y=y_train)

mlflow.sklearn.autolog(disable=True)
with mlflow.start_run(run_name="genie_code_fraud_xgboost") as mlflow_run:
    training_dataset = mlflow.data.from_pandas(pdf, name="transactions_features", targets=target_col)
    mlflow.log_input(training_dataset, context="training")
    pipeline.fit(X_train, y_train, classifier__sample_weight=sample_weights)
    val_f1 = f1_score(y_val, pipeline.predict(X_val), average="weighted")
    mlflow.log_metric("val_f1_score", val_f1)
    signature = infer_signature(X_train, pipeline.predict(X_train))
    # cloudpickle keeps the model self-contained (no databricks-automl-runtime) so it loads on serverless.
    mlflow.sklearn.log_model(pipeline, name="model", input_example=X_train.iloc[[0]],
                             signature=signature, serialization_format="cloudpickle")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Register the new model as our A/B "candidate"
# MAGIC We register this XGBoost model under the same `dbdemos_fsi_fraud` name with the `candidate` alias,
# MAGIC so the next notebook can A/B test it against the current `prod` model.

# COMMAND ----------

from mlflow import MlflowClient
mlflow.set_registry_uri('databricks-uc')
client = MlflowClient()
new_model = mlflow.register_model(f'runs:/{mlflow_run.info.run_id}/model', f"{catalog}.{db}.{model_name}")
print(f"Updating model to version {new_model.version}")
client.set_registered_model_alias(name=f"{catalog}.{db}.{model_name}", alias="candidate", version=new_model.version)


# COMMAND ----------

# MAGIC %md
# MAGIC
# MAGIC ## Our new model is now ready !
# MAGIC
# MAGIC We're ready to deploy it in Production. However, as we're handling customer transactions in real-time, we want to make sure we start with a small, non disruptive release:
# MAGIC
# MAGIC * Without making any production outage
# MAGIC * Route only a subset of the traffic to our new model
# MAGIC * Measure model efficiency & ensure it's performing better.
# MAGIC
# MAGIC This is non-trivial and typically requests a full devops team. Thanksfully, Databricks makes this simple.
# MAGIC
# MAGIC Open the next notebook [04.5-AB-testing-model-serving-fraud]($./04.5-AB-testing-model-serving-fraud) to deploy our model and start routing a small subset of the requests to our new model!
