# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

#Explore raw turbine status data

sdf = spark.read.format("json").load("/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/historical_turbine_status")
display(sdf)

# COMMAND ----------

#Explore raw sensor data
sdf = spark.read.format("parquet").load("/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/incoming_data")
display(sdf)

# COMMAND ----------

#Explore raw turbine status data

sdf = spark.read.format("json").load("/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/historical_turbine_status")
display(sdf)

spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "json")
        .option("cloudFiles.inferColumnTypes", "true")
        .load("/Volumes/main_build/dbdemos_iot_platform/turbine_raw_landing/turbine")
