name: Sync Fork with Upstream

on:
  # Runs every day at midnight
  schedule:
    - cron: '0 0 * * *'
  
  # Allows manual trigger from the Actions tab
  workflow_dispatch:
  
  # Optional: Trigger on push to your fork
  # push:
  #   branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      # Check out your fork
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main  # or your default branch name
      
      # Add upstream remote
      - name: Add upstream remote
        run: |
          git remote add upstream ${{ vars.UPSTREAM_REPO_URL }}
          git remote -v
      
      # Fetch all branches and tags from upstream
      - name: Fetch upstream
        run: |
          git fetch upstream --tags --force
      
      # Check if upstream has diverged
      - name: Check for divergence
        id: check_diverge
        run: |
          git merge-base --is-ancestor upstream/main main || echo "has_diverged=true" >> $GITHUB_OUTPUT
      
      # Create sync branch and merge if diverged
      - name: Sync with upstream
        if: steps.check_diverge.outputs.has_diverged == 'true'
        run: |
          # Create and checkout sync branch
          git checkout -b sync-upstream
          
          # Try to merge upstream changes
          git merge upstream/main
          
          # Push to your fork
          git push origin sync-upstream
      
      # Create pull request if changes were pushed
      - name: Create Pull Request
        if: steps.check_diverge.outputs.has_diverged == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'chore: sync fork with upstream'
          body: |
            This PR syncs your fork with the upstream repository.
            
            Changes from upstream have been merged into this PR for review.
          branch: sync-upstream
          base: main
          delete-branch: true
