# Databricks notebook source
# MAGIC %md-sandbox
# MAGIC
# MAGIC # Accelerating Data Science with Databricks Genie Code
# MAGIC
# MAGIC ##  Predicting patient readmission risk with the Databricks Data Science Agent
# MAGIC
# MAGIC <img src="https://github.com/databricks-demos/dbdemos-resources/blob/main/images/hls/patient-readmission/patient-risk-ds-flow-2.png?raw=true" width="700px" style="float: right; margin-left: 10px;" />
# MAGIC
# MAGIC
# MAGIC In this notebook, we will explore how to use Databricks Genie Code to generate the training code for our patient readmission risk model and deploy it in production.
# MAGIC
# MAGIC Databricks Genie Code allows you to quickly generate baseline models and code.
# MAGIC
# MAGIC ML experts can accelerate their workflow by fast-forwarding through the usual trial-and-error and focus on customizations using their domain knowledge, and citizen data scientists can quickly achieve usable results with a low-code approach.
# MAGIC
# MAGIC
# MAGIC <!-- Collect usage data (view). Remove it to disable collection. View README for more details.  -->
# MAGIC <img width="1px" src="https://ppxrzfxige.execute-api.us-west-2.amazonaws.com/v1/analytics?category=lakehouse&notebook=04.2-AutoML-patient-admission-risk&demo_name=lakehouse-patient-readmission&event=VIEW">

# COMMAND ----------

# DBTITLE 1,Make sure we have the latest SDK (used in the helper)
# MAGIC %pip install mlflow==3.14.0 databricks-sdk scikit-learn optuna
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %run ../_resources/00-setup $reset_all_data=false

# COMMAND ----------

# MAGIC %md
# MAGIC ### Getting our training dataset 
# MAGIC
# MAGIC Let's use the our training dataset determining the readmission after 30 days for all our population. We will use that as our training label and what we want our model to predict.

# COMMAND ----------

training_dataset = spark.table('training_dataset')
training_dataset.display()

# COMMAND ----------

# MAGIC %md
# MAGIC ### Define what features to look up for our model
# MAGIC
# MAGIC Let's only keep the relevant features for our model training. We are removing columns such as `SSN` or `IDs`.
# MAGIC
# MAGIC This step could also be done selecting the training_dataset table from the UI and selecting the column of interest.
# MAGIC
# MAGIC *Note: this could also be retrieved from our Feature Store tables. For more details on that open the companion notebook.*

# COMMAND ----------

feature_names = ['MARITAL_M', 'MARITAL_S', 'RACE_asian', 'RACE_black', 'RACE_hawaiian', 'RACE_other', 'RACE_white', 'ETHNICITY_hispanic', 'ETHNICITY_nonhispanic', 'GENDER_F', 'GENDER_M', 'INCOME'] \
              + ['BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'enc_length', 'ENCOUNTERCLASS_ambulatory', 'ENCOUNTERCLASS_emergency', 'ENCOUNTERCLASS_hospice', 'ENCOUNTERCLASS_inpatient', 'ENCOUNTERCLASS_outpatient', 'ENCOUNTERCLASS_wellness'] \
              + ['age_at_encounter'] \
              + ['30_DAY_READMISSION']

# COMMAND ----------

# MAGIC %md-sandbox
# MAGIC
# MAGIC ## Accelerating patient readmission model creation with Databricks Genie Code
# MAGIC The Data Science Agent (Genie Code) elevates the Databricks Assistant from a helpful copilot into a true autonomous partner for data science and analytics. Fully integrated with Databricks Notebooks and the SQL Editor, the [Data Science Agent](https://www.databricks.com/blog/introducing-databricks-assistant-data-science-agent) let's you analyze your data and build ML models in a few clicks/prompt.
# MAGIC <img src="https://www.databricks.com/sites/default/files/2025-09/AgentModeOG1Border.png?v=1756901406" width="500px" style="float: right"/>
# MAGIC
# MAGIC - It transforms Databricks Assistant into an autonomous partner for data science and analytics tasks in Notebooks and the SQL Editor.
# MAGIC
# MAGIC - It can explore data, generate and run code, and fix errors, all from a single prompt. This can cut hours of work to minutes.
# MAGIC
# MAGIC - Purpose-built for common data science tasks and grounded in Unity Catalog for seamless, governed access to your data.
# MAGIC
# MAGIC <br style="clear: both">
# MAGIC
# MAGIC ### Using Databricks Genie Code with our readmission risk
# MAGIC
# MAGIC All we have to do is describe our problem to Genie Code and point it at our training dataset, with `30_DAY_READMISSION` as our prediction target.
# MAGIC
# MAGIC Below is the training code Genie Code generated for us — a standard scikit-learn pipeline, fully tracked in MLflow (parameters, metrics and **dataset lineage**) for reproducibility and governance.

# COMMAND ----------

# DBTITLE 1,Training code generated by Databricks Genie Code
import mlflow, optuna
from mlflow.models.signature import infer_signature
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import f1_score

model_name = "dbdemos_hls_patient_readmission"
target_col = "30_DAY_READMISSION"
# Shared experiment path (must be a workspace /Shared path, not a local one, so it works in
# jobs running from the GitHub repo). set_experiment creates it if missing, or reuses it.
xp_path = "/Shared/dbdemos/experiments/lakehouse-patient-admission"
mlflow.set_experiment(xp_path)
DBDemos.set_experiment_permission(xp_path)

pdf = training_dataset.select(feature_names).toPandas()
X = pdf.drop(columns=[target_col])
y = pdf[target_col]
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Standard sklearn preprocessing: impute numerics, ordinal-encode categoricals.
num_cols = X.select_dtypes(include="number").columns.tolist()
cat_cols = [c for c in X.columns if c not in num_cols]
preprocessor = ColumnTransformer([
    ("num", SimpleImputer(strategy="median"), num_cols),
    ("cat", Pipeline([("imp", SimpleImputer(strategy="most_frequent")),
                      ("enc", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1))]), cat_cols),
])

def build_pipeline(params):
    return Pipeline([("preprocessor", preprocessor),
                     ("classifier", RandomForestClassifier(random_state=42, n_jobs=-1, **params))])

mlflow.sklearn.autolog(disable=True)
with mlflow.start_run(run_name="genie_code_patient_readmission") as genie_run:
    # Track dataset lineage: link the training data to this run for full governance.
    training_dataset_mlflow = mlflow.data.from_pandas(pdf, name="patient_readmission_features", targets=target_col)
    mlflow.log_input(training_dataset_mlflow, context="training")

    # Hyperparameter search with Optuna, each trial logged to MLflow as a nested run.
    def objective(trial):
        params = {
            "n_estimators": trial.suggest_int("n_estimators", 50, 300),
            "max_depth": trial.suggest_int("max_depth", 3, 12),
            "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20),
        }
        with mlflow.start_run(nested=True, run_name=f"trial_{trial.number}"):
            mlflow.log_params(params)
            score = cross_val_score(build_pipeline(params), X_train, y_train, cv=3, scoring="f1_weighted").mean()
            mlflow.log_metric("cv_f1_weighted", score)
        return score

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=20)
    mlflow.log_params(study.best_params)

    # Refit the best model on the full training split and evaluate on the hold-out set.
    best_model = build_pipeline(study.best_params)
    best_model.fit(X_train, y_train)
    val_f1 = f1_score(y_val, best_model.predict(X_val), average="weighted")
    mlflow.log_metric("val_f1_score", val_f1)

    signature = infer_signature(X_train, best_model.predict(X_train))
    # cloudpickle keeps the model self-contained (no databricks-automl-runtime) so it loads on serverless.
    mlflow.sklearn.log_model(best_model, name="model", input_example=X_train.iloc[[0]],
                             signature=signature, serialization_format="cloudpickle")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Deploying our model in production
# MAGIC
# MAGIC Our model is now ready. We can review the code generated by Genie Code and customize it if required.
# MAGIC
# MAGIC For this demo, we'll consider that our model is ready and deploy it in production in our Unity Catalog Model Registry:

# COMMAND ----------

#Enable Unity Catalog with mlflow registry
mlflow.set_registry_uri('databricks-uc')
    
model_registered = mlflow.register_model(f"runs:/{genie_run.info.run_id}/model", f"{catalog}.{db}.{model_name}")

#Move the model in production
print("registering model version "+model_registered.version+" as production model")
client = mlflow.tracking.MlflowClient()
client.set_registered_model_alias(name=f"{catalog}.{db}.{model_name}", alias="prod", version=model_registered.version)

#Make sure all other users can access the model for our demo
#DBDemos.set_model_permission(f"{catalog}.{db}.{model_name}", "ALL_PRIVILEGES", "account users")

# COMMAND ----------

# MAGIC %md
# MAGIC We just moved our Genie Code-generated model as production ready!
# MAGIC
# MAGIC Open the Unity Catalog [the dbdemos_hls_patient_readmission model](/explore/data/models/dbdemos/hls_patient_readmission/dbdemos_hls_patient_readmission) to explore its artifact and analyze the parameters used, including traceability to the notebook used for its creation.

# COMMAND ----------

# MAGIC %md
# MAGIC
# MAGIC ## Our model predicting default risks is now deployed in production
# MAGIC
# MAGIC So far we have:
# MAGIC * ingested all required data in a single source of truth using the OMOP data model,
# MAGIC * properly secured all data (including granting granular access controls, masked PII data, applied column level filtering),
# MAGIC * enhanced that data through feature engineering (and Feature Store as an option),
# MAGIC * used Databricks Genie Code and MLflow to build and track a machine learning model,
# MAGIC * registered the model.
# MAGIC
# MAGIC ### Next steps
# MAGIC We're now ready to use our model use it for:
# MAGIC
# MAGIC - Batch inferences in notebook [04.3-Batch-Scoring-patient-readmission]($./04.3-Batch-Scoring-patient-readmission) to start using it for identifying patient at risk and providing custom care to reduce readmission risk,
# MAGIC - Real time inference with [04.4-Model-Serving-patient-readmission]($./04.4-Model-Serving-patient-readmission) to enable real-time capabilities and instantly get insight for a specific patient.
# MAGIC - Explain model for our entire population or a specific patient to understand the risk factors and further personalize care with [04.5-Explainability-patient-readmission]($./04.5-Explainability-patient-readmission)
